DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE PRODUCT (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL,
email VARCHAR(30),
phone VARCHAR(11),
product VARCHAR(30) NOT NULL,
serialNumber VARCHAR(10) NOT NULL,
purchasePrice DECIMAL(8,2) NOT NULL,
purchaseDate DATE,
contact BIT
);