DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE PRODUCT (
id INT AUTO_INCREMENT PRIMARY KEY,
productName VARCHAR(30) NOT NULL,
serialNumber VARCHAR(10) NOT NULL,
purchasePrice DECIMAL(8,2) NOT NULL,
purchaseDate DATE
);

DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50),
email VARCHAR(30),
phone VARCHAR(11),
password VARCHAR(20),
admin BIT
);